# Generated by Django 2.2.13 on 2020-12-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='testt test'),
            preserve_default=False,
        ),
    ]
