# Generated by Django 2.2.13 on 2020-12-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_ordered_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
