# Generated by Django 2.2.13 on 2021-01-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='amounts',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
