# Generated by Django 2.2.13 on 2021-01-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_coupon_amounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='amounts',
            new_name='amount',
        ),
    ]
